### ISSUE TITLE
npmjs.com installation instructions broken

### ISSUE THREAD

**Issue by derrelldurrett** [mere/browserify-shader#2]
Not horribly. Just confusingly.

Currently, the page at https://www.npmjs.com/package/browserify-shader contains the following text:
    super simple browserify transform for loading webgl shaders

    ###Installation:

    npm install browserify-shaders

Note the trailing 's' in the ```Installation``` instruction's name for the module.

**Comment by mere** [comment]
Thanks for raising this, @derrelldurrett! :smiley_cat: 
Just updated the readme.
